apiVersion: v1
kind: Pod
metadata:
  name: multitool
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool:latest
    env:
    - name: HTTP_PORT
      value: "1180"
    command: ["/bin/sh", "-c", "sleep 3600"]
